#@ load("@ytt:data", "data")
#@ load("@ytt:library", "library")
#@ load("@ytt:template", "template")
#@ load("/namespaces.star", "system_namespace")
#@ load("/networking/ingress.lib.yml", "ingress")

#@ def logging_values():
system_domain: #@ data.values.system_domain
system_namespace: #@ system_namespace()

app_log_destinations:
#@ for/end destination in data.values.app_log_destinations:
#@overlay/append
- #@ destination

#@ end
#@ logging = library.get("cf-k8s-logging")
--- #@ template.replace(logging.with_data_values(logging_values()).eval())

--- #@ ingress("log-cache-external", ["log-cache." + data.values.system_domain], "log-cache", 8083)
