---
apiVersion: kapp.k14s.io/v1alpha1
kind: Config
metadata:
  name: kapp-ingress-secret-name
templateRules:
- resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: v1, kind: Secret}
  affectedResources:
    objectReferences:
    - path: [spec, tls, {allIndexes: true}]
      resourceMatchers:
      - apiVersionKindMatcher: {apiVersion: networking.k8s.io/v1beta1, kind: Ingress}
      nameKey: secretName
